version: '3'
services:
    app:
        build: .
        restart: always
        environment:
            DEBUG: 1
        volumes:
            # Maps our current project directory `.` to
            # our working directory in the container
            - ./:/app/
        ports:
            - '8000:80'
