version: '3'
services:
    app:
        build: .
        restart: always
        environment:
            DEBUG: 1
        volumes:
            # Maps our current project directory `.` to
            # our working directory in the container
            - ./:/app/
        ports:
            - '8000:80'
    db:
        image: postgres:14.5-alpine
        ports:
            - '${DB_PORT}:5432'
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_SCHEMA=${DB_SCHEMA}
            - DB_ADMIN_USER=${DB_ADMIN_USER}
            - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
            - DB_APP_USER=${DB_APP_USER}
            - DB_APP_PASSWORD=${DB_APP_PASSWORD}
        volumes:
            - ./scripts/db:/docker-entrypoint-initdb.d/ # Run setup scripts
            - pg-data:/var/lib/postgresql/data/ # Make db data persist

volumes:
    pg-data:
